import { Head, Link, router, useForm, usePage } from '@inertiajs/react';
import { routerPostWithOffline } from '@/utils/offlineQueue';
import { useState } from 'react';
import InputError from '@/Components/InputError';
import InputLabel from '@/Components/InputLabel';
import PatientRecordSidebar from '@/Components/PatientRecordSidebar';
import PrimaryButton from '@/Components/PrimaryButton';
import AppHeaderNav from '@/Components/AppHeaderNav';
import ProfileMenu from '@/Components/ProfileMenu';

const dayFields = [
    { key: 'presentation', label: 'Presentation', rows: 3 },
    { key: 'care_delivered', label: 'Care delivered', rows: 3 },
    { key: 'medication_summary', label: 'Medication summary', rows: 2 },
    { key: 'risks_changes', label: 'Risks / changes', rows: 2 },
    { key: 'handover_notes', label: 'Handover notes', rows: 4 },
];

const nightFields = [
    { key: 'sleep_summary', label: 'Sleep summary', rows: 3 },
    { key: 'disturbances', label: 'Disturbances', rows: 2 },
    { key: 'night_medications', label: 'Night medications', rows: 2 },
    { key: 'seizure_respiratory_events', label: 'Seizure / respiratory events', rows: 2 },
    { key: 'morning_priorities', label: 'Morning priorities', rows: 3 },
];

function HandoverTimeline({ timeline = [] }) {
    if (!timeline.length) {
        return null;
    }

    return (
        <div className="mt-4 rounded-xl border border-slate-200 bg-slate-50 p-4">
            <h4 className="text-xs font-semibold uppercase tracking-wide text-slate-500">Chronological follow-up</h4>
            <ol className="mt-3 space-y-2">
                {timeline.map((item, index) => (
                    <li
                        key={`${item.at}-${index}`}
                        className={`rounded-lg border px-3 py-2 text-sm ${
                            item.requiresFollowUp
                                ? 'border-amber-200 bg-amber-50 text-amber-900'
                                : 'border-slate-200 bg-white text-slate-700'
                        }`}
                    >
                        <div className="flex flex-wrap items-center justify-between gap-2 text-xs text-slate-500">
                            <span className="font-semibold uppercase tracking-wide">{item.category}</span>
                            <span>{item.atLabel}</span>
                        </div>
                        <p className="mt-1 whitespace-pre-wrap">{item.summary}</p>
                    </li>
                ))}
            </ol>
        </div>
    );
}

function HandoverDetail({ handover, patientSlug, authUserId, onAcknowledge, acknowledging }) {
    const fields = handover.shiftType === 'day' ? dayFields : nightFields;
    const source = handover.shiftType === 'day' ? handover.day : handover.night;
    const keyMap = {
        presentation: 'presentation',
        care_delivered: 'careDelivered',
        medication_summary: 'medicationSummary',
        risks_changes: 'risksChanges',
        handover_notes: 'handoverNotes',
        sleep_summary: 'sleepSummary',
        disturbances: 'disturbances',
        night_medications: 'nightMedications',
        seizure_respiratory_events: 'seizureRespiratoryEvents',
        morning_priorities: 'morningPriorities',
    };

    const canAcknowledge = !handover.acknowledgedAt
        && handover.author?.id
        && handover.author.id !== authUserId;

    return (
        <li className="rounded-xl border border-slate-200 p-4">
            <div className="mb-3 flex flex-wrap items-center justify-between gap-2">
                <div>
                    <span
                        className={`inline-block rounded-full px-2 py-0.5 text-[10px] font-bold uppercase tracking-wide ${
                            handover.shiftType === 'day'
                                ? 'bg-amber-100 text-amber-800'
                                : 'bg-indigo-100 text-indigo-800'
                        }`}
                    >
                        {handover.shiftType} shift
                    </span>
                    {handover.autoGenerated && (
                        <span className="ml-2 inline-block rounded-full bg-sky-100 px-2 py-0.5 text-[10px] font-bold text-sky-800">
                            AUTO-GENERATED
                        </span>
                    )}
                    <p className="mt-1 text-sm font-semibold text-slate-800">{handover.shiftDateLabel}</p>
                    {handover.periodStartLabel && handover.periodEndLabel && (
                        <p className="mt-0.5 text-xs text-slate-500">
                            Summary period: {handover.periodStartLabel} – {handover.periodEndLabel}
                        </p>
                    )}
                    {handover.controlledDrugReconciliationComplete && (
                        <span className="mt-1 inline-block rounded-full bg-emerald-100 px-2 py-0.5 text-[10px] font-bold text-emerald-700">CD RECONCILED</span>
                    )}
                    {handover.acknowledgedAt ? (
                        <p className="mt-2 text-xs text-emerald-700">
                            Acknowledged {handover.acknowledgedAtLabel} by {handover.acknowledgedBy?.name || 'staff'}
                        </p>
                    ) : (
                        <p className="mt-2 text-xs font-medium text-amber-700">Awaiting incoming staff acknowledgement</p>
                    )}
                </div>
                <div className="text-right text-xs text-slate-500">
                    <p>{handover.recordedAtLabel}</p>
                    <p className="font-medium text-slate-700">{handover.author?.name || 'Unknown'}</p>
                </div>
            </div>
            {handover.autoSnapshot?.timeline?.length > 0 && (
                <HandoverTimeline timeline={handover.autoSnapshot.timeline} />
            )}
            <dl className="mt-4 space-y-3">
                {fields.map((field) => {
                    const value = source?.[keyMap[field.key]];
                    if (!value) {
                        return null;
                    }
                    return (
                        <div key={field.key}>
                            <dt className="text-[10px] font-semibold uppercase tracking-wide text-slate-500">{field.label}</dt>
                            <dd className="mt-1 whitespace-pre-wrap text-sm text-slate-700">{value}</dd>
                        </div>
                    );
                })}
            </dl>
            {canAcknowledge && (
                <div className="mt-4 flex justify-end">
                    <PrimaryButton
                        type="button"
                        disabled={acknowledging}
                        onClick={() => onAcknowledge(handover.id)}
                    >
                        {acknowledging ? 'Recording…' : 'Acknowledge receipt'}
                    </PrimaryButton>
                </div>
            )}
        </li>
    );
}

export default function PatientHandovers({
    patientSlug,
    patient = null,
    handovers = [],
    pendingAcknowledgementCount = 0,
    controlledDrugStock = [],
    witnessStaff = [],
    prefill = null,
}) {
    const authUser = usePage().props?.auth?.user;
    const successMessage = usePage().props?.flash?.success;
    const patientName = patient?.name || 'Unknown Patient';
    const [shiftType, setShiftType] = useState(prefill?.shiftType || 'day');
    const [autoSnapshot, setAutoSnapshot] = useState(null);
    const [generating, setGenerating] = useState(false);
    const [generateError, setGenerateError] = useState('');
    const [acknowledgingId, setAcknowledgingId] = useState(null);
    const [reconciliations, setReconciliations] = useState(() =>
        (controlledDrugStock || []).map((item) => ({
            medication_id: item.medicationId,
            medication_name: item.medicationName,
            system_balance: item.balance,
            unit: item.unit,
            counted_balance: String(item.balance ?? ''),
            witness_user_id: '',
            notes: '',
        })),
    );

    const { data, setData, processing, errors, reset } = useForm({
        shift_type: prefill?.shiftType || 'day',
        shift_date: prefill?.shiftDate || new Date().toISOString().slice(0, 10),
        schedule_id: prefill?.scheduleId ? String(prefill.scheduleId) : '',
        presentation: '',
        care_delivered: '',
        medication_summary: '',
        risks_changes: '',
        handover_notes: '',
        sleep_summary: '',
        disturbances: '',
        night_medications: '',
        seizure_respiratory_events: '',
        morning_priorities: '',
        auto_generated: false,
        auto_snapshot: null,
    });

    const switchShiftType = (type) => {
        setShiftType(type);
        setData('shift_type', type);
        setAutoSnapshot(null);
        setData('auto_generated', false);
        setData('auto_snapshot', null);
    };

    const generateSummary = async () => {
        setGenerating(true);
        setGenerateError('');
        try {
            const params = new URLSearchParams({
                shift_type: data.shift_type,
                shift_date: data.shift_date,
            });
            if (data.schedule_id) {
                params.set('schedule_id', data.schedule_id);
            }
            const response = await fetch(`${route('patients.handovers.generate', patientSlug)}?${params.toString()}`, {
                headers: { Accept: 'application/json' },
                credentials: 'same-origin',
            });
            if (!response.ok) {
                throw new Error('Could not generate handover summary.');
            }
            const draft = await response.json();
            setAutoSnapshot(draft);
            setData('auto_generated', true);
            setData('auto_snapshot', draft);
            const suggested = draft.suggestedFields || {};
            Object.entries(suggested).forEach(([key, value]) => {
                if (value) {
                    setData(key, value);
                }
            });
        } catch (error) {
            setGenerateError(error.message || 'Could not generate handover summary.');
        } finally {
            setGenerating(false);
        }
    };

    const acknowledgeHandover = (handoverId) => {
        setAcknowledgingId(handoverId);
        router.post(route('patients.handovers.acknowledge', { patient: patientSlug, handover: handoverId }), {}, {
            preserveScroll: true,
            onFinish: () => setAcknowledgingId(null),
        });
    };

    const submitHandover = (event) => {
        event.preventDefault();
        routerPostWithOffline(route('patients.handovers.store', patientSlug), {
            ...data,
            auto_generated: data.auto_generated,
            auto_snapshot: data.auto_snapshot,
            controlled_reconciliations: reconciliations.map((row) => ({
                medication_id: row.medication_id,
                counted_balance: parseFloat(row.counted_balance, 10),
                witness_user_id: row.witness_user_id ? parseInt(row.witness_user_id, 10) : null,
                notes: row.notes || null,
            })),
        }, {
            onSuccess: () => {
                reset(
                    'presentation',
                    'care_delivered',
                    'medication_summary',
                    'risks_changes',
                    'handover_notes',
                    'sleep_summary',
                    'disturbances',
                    'night_medications',
                    'seizure_respiratory_events',
                    'morning_priorities'
                );
                setData('auto_generated', false);
                setData('auto_snapshot', null);
                setAutoSnapshot(null);
            },
        });
    };

    const activeFields = shiftType === 'day' ? dayFields : nightFields;

    return (
        <>
            <Head title={`Handovers — ${patientName}`} />

            <div className="min-h-screen bg-slate-100 text-slate-700">
                <div className="flex w-full">
                    <PatientRecordSidebar patientSlug={patientSlug} active="handovers" />

                    <main className="flex-1 p-4 sm:p-6 lg:p-8">
                        <header className="mb-4 flex flex-wrap items-center justify-between gap-3 rounded-2xl bg-white px-5 py-3">
                            <AppHeaderNav active="patients" />
                            <ProfileMenu />
                        </header>

                        <div className="mb-4 flex items-center gap-2 text-xs font-medium text-slate-500">
                            <Link href={route('dashboard')} className="hover:text-slate-700">Dashboard</Link>
                            <span>/</span>
                            <Link href={route('patients')} className="hover:text-slate-700">Patients</Link>
                            <span>/</span>
                            <Link href={route('patients.show', patientSlug)} className="hover:text-slate-700">{patientName}</Link>
                            <span>/</span>
                            <span className="text-slate-900">Handovers</span>
                        </div>

                        {successMessage && (
                            <div className="mb-4 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-800">
                                {successMessage}
                            </div>
                        )}

                        <section className="mb-6 rounded-2xl bg-white p-5 shadow-sm">
                            <h1 className="text-2xl font-bold text-slate-900">Shift handover</h1>
                            <p className="mt-1 text-sm text-slate-500">
                                Structured day and night summaries for incoming staff — auto-generated from care notes, observations, incidents, medications, and outstanding follow-ups.
                            </p>

                            {pendingAcknowledgementCount > 0 && (
                                <div className="mt-4 rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-900">
                                    <span className="font-semibold">{pendingAcknowledgementCount} handover{pendingAcknowledgementCount === 1 ? '' : 's'}</span>
                                    {' '}awaiting acknowledgement from incoming staff.
                                </div>
                            )}

                            <form onSubmit={submitHandover} className="mt-6 rounded-2xl border border-slate-200 bg-slate-50 p-5">
                                <div className="mb-4 flex flex-wrap items-end gap-4">
                                    <div>
                                        <InputLabel htmlFor="shift_date" value="Shift date" />
                                        <input
                                            id="shift_date"
                                            type="date"
                                            required
                                            value={data.shift_date}
                                            onChange={(e) => setData('shift_date', e.target.value)}
                                            className="mt-1 block rounded-md border-slate-300 shadow-sm focus:border-emerald-500 focus:ring-emerald-500"
                                        />
                                        <InputError message={errors.shift_date} className="mt-2" />
                                    </div>
                                    <div>
                                        <p className="text-sm font-medium text-slate-700">Handover type</p>
                                        <div className="mt-2 inline-flex rounded-lg border border-slate-200 bg-white p-1">
                                            <button
                                                type="button"
                                                onClick={() => switchShiftType('day')}
                                                className={`rounded-md px-4 py-2 text-sm font-semibold ${
                                                    shiftType === 'day'
                                                        ? 'bg-amber-500 text-white'
                                                        : 'text-slate-600 hover:bg-slate-50'
                                                }`}
                                            >
                                                Day
                                            </button>
                                            <button
                                                type="button"
                                                onClick={() => switchShiftType('night')}
                                                className={`rounded-md px-4 py-2 text-sm font-semibold ${
                                                    shiftType === 'night'
                                                        ? 'bg-indigo-700 text-white'
                                                        : 'text-slate-600 hover:bg-slate-50'
                                                }`}
                                            >
                                                Night
                                            </button>
                                        </div>
                                    </div>
                                    {/* <div>
                                        <p className="text-sm font-medium text-slate-700">&nbsp;</p>
                                        <button
                                            type="button"
                                            onClick={generateSummary}
                                            disabled={generating}
                                            className="mt-2 rounded-lg border border-sky-300 bg-sky-50 px-4 py-2 text-sm font-semibold text-sky-800 hover:bg-sky-100 disabled:opacity-60"
                                        >
                                            {generating ? 'Generating…' : 'Generate automated summary'}
                                        </button>
                                        {generateError && (
                                            <p className="mt-2 text-xs text-red-600">{generateError}</p>
                                        )}
                                    </div> */}
                                </div>

                                {autoSnapshot?.timeline?.length > 0 && (
                                    <div className="mb-4">
                                        <p className="mb-2 text-sm font-medium text-slate-700">
                                            Automated draft ({autoSnapshot.periodStartLabel} – {autoSnapshot.periodEndLabel})
                                        </p>
                                        <HandoverTimeline timeline={autoSnapshot.timeline} />
                                    </div>
                                )}

                                {data.schedule_id && (
                                    <input type="hidden" name="schedule_id" value={data.schedule_id} />
                                )}

                                <div className="space-y-4">
                                    {activeFields.map((field) => (
                                        <div key={field.key}>
                                            <InputLabel htmlFor={field.key} value={field.label} />
                                            <textarea
                                                id={field.key}
                                                rows={field.rows}
                                                value={data[field.key]}
                                                onChange={(e) => setData(field.key, e.target.value)}
                                                className="mt-1 block w-full rounded-md border-slate-300 shadow-sm focus:border-emerald-500 focus:ring-emerald-500"
                                            />
                                            <InputError message={errors[field.key]} className="mt-2" />
                                        </div>
                                    ))}
                                </div>

                                {controlledDrugStock.length > 0 && (
                                    <div className="mt-6 rounded-xl border border-amber-200 bg-amber-50 p-4">
                                        <h3 className="text-sm font-semibold text-amber-900">Controlled drug stock reconciliation *</h3>
                                        <p className="mt-1 text-xs text-amber-800">
                                            Required at every shift handover. Enter the physical count and dual staff sign-off for each controlled drug.
                                        </p>
                                        <InputError message={errors.controlled_reconciliations} className="mt-2" />
                                        <div className="mt-4 space-y-4">
                                            {reconciliations.map((row, index) => (
                                                <div key={row.medication_id} className="rounded-lg border border-amber-200 bg-white p-3">
                                                    <p className="text-sm font-semibold text-slate-900">{row.medication_name}</p>
                                                    <p className="text-xs text-slate-500">System balance: {row.system_balance} {row.unit}</p>
                                                    <div className="mt-2 grid gap-3 sm:grid-cols-3">
                                                        <div>
                                                            <InputLabel value="Physical count *" />
                                                            <input
                                                                type="number"
                                                                min="0"
                                                                step="0.01"
                                                                required
                                                                value={row.counted_balance}
                                                                onChange={(e) => {
                                                                    const next = [...reconciliations];
                                                                    next[index] = { ...next[index], counted_balance: e.target.value };
                                                                    setReconciliations(next);
                                                                }}
                                                                className="mt-1 block w-full rounded-md border-slate-300 text-sm"
                                                            />
                                                        </div>
                                                        <div>
                                                            <InputLabel value="Witness (dual sign-off) *" />
                                                            <select
                                                                required
                                                                value={row.witness_user_id}
                                                                onChange={(e) => {
                                                                    const next = [...reconciliations];
                                                                    next[index] = { ...next[index], witness_user_id: e.target.value };
                                                                    setReconciliations(next);
                                                                }}
                                                                className="mt-1 block w-full rounded-md border-slate-300 text-sm"
                                                            >
                                                                <option value="">Select witness</option>
                                                                {witnessStaff.filter((s) => s.id !== authUser?.id).map((s) => (
                                                                    <option key={s.id} value={s.id}>{s.name}</option>
                                                                ))}
                                                            </select>
                                                        </div>
                                                        <div>
                                                            <InputLabel value="Notes" />
                                                            <input
                                                                type="text"
                                                                value={row.notes}
                                                                onChange={(e) => {
                                                                    const next = [...reconciliations];
                                                                    next[index] = { ...next[index], notes: e.target.value };
                                                                    setReconciliations(next);
                                                                }}
                                                                className="mt-1 block w-full rounded-md border-slate-300 text-sm"
                                                                placeholder="Optional"
                                                            />
                                                        </div>
                                                    </div>
                                                </div>
                                            ))}
                                        </div>
                                    </div>
                                )}

                                <div className="mt-4 flex justify-end">
                                    <PrimaryButton disabled={processing}>
                                        {processing ? 'Saving…' : `Save ${shiftType} handover`}
                                    </PrimaryButton>
                                </div>
                            </form>
                        </section>

                        <section className="rounded-2xl bg-white p-5 shadow-sm">
                            <h2 className="mb-4 text-lg font-semibold text-slate-800">Handover history</h2>
                            {handovers.length === 0 ? (
                                <p className="rounded-xl bg-slate-50 p-8 text-center text-sm text-slate-500">
                                    No handovers recorded yet.
                                </p>
                            ) : (
                                <ul className="space-y-3">
                                    {handovers.map((entry) => (
                                        <HandoverDetail
                                            key={entry.id}
                                            handover={entry}
                                            patientSlug={patientSlug}
                                            authUserId={authUser?.id}
                                            onAcknowledge={acknowledgeHandover}
                                            acknowledging={acknowledgingId === entry.id}
                                        />
                                    ))}
                                </ul>
                            )}
                        </section>
                    </main>
                </div>
            </div>
        </>
    );
}
