<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Compliance & Training Report</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color: #0f172a; }
        h1 { margin: 0 0 8px; font-size: 18px; text-align: center; }
        .meta { margin-bottom: 12px; color: #475569; text-align: center; }
        .stats { margin-bottom: 14px; text-align: center; }
        .stats span { display: inline-block; margin-right: 14px; }
        table { width: 100%; border-collapse: collapse; }
        th, td { border: 1px solid #cbd5e1; padding: 6px; vertical-align: top; }
        th { background: #f1f5f9; text-align: left; }
        .logo-wrap { text-align: center; margin-bottom: 14px; }
        .logo-fallback { font-size: 30px; font-weight: 700; text-align: center; margin-bottom: 14px; }
        .footer-meta {
            position: fixed;
            right: 18px;
            bottom: 12px;
            font-size: 10px;
            color: #475569;
            text-align: right;
        }
    </style>
</head>
<body>
    @php
        $logoPath = public_path('images/login-logo.png');
        $logoData = null;
        if (file_exists($logoPath)) {
            $logoData = 'data:image/png;base64,'.base64_encode(file_get_contents($logoPath));
        }
    @endphp

    @if($logoData)
        <div class="logo-wrap">
            <img src="{{ $logoData }}" alt="Allocare logo" style="height: 110px;" />
        </div>
    @else
        <div class="logo-fallback">Allocare</div>
    @endif

    <h1>Compliance & Training Report</h1>
    <div class="meta"></div>
    <div class="stats">
        <span><strong>Total Staff:</strong> {{ $stats['totalStaff'] ?? 0 }}</span>
        <span><strong>Fully Compliant:</strong> {{ $stats['fullyCompliant'] ?? 0 }}</span>
        <span><strong>Due Soon:</strong> {{ $stats['dueSoon'] ?? 0 }}</span>
        <span><strong>Overdue Critical:</strong> {{ $stats['overdueCritical'] ?? 0 }}</span>
        <span><strong>Compliance Rate:</strong> {{ $stats['complianceRate'] ?? 0 }}%</span>
    </div>

    <table>
        <thead>
            <tr>
                <th>Staff</th>
                <th>Role</th>
                <th>Risk</th>
                <th>Training</th>
                <th>Competencies</th>
                <th>Supervisions</th>
                <th>DBS</th>
                <th>Documents</th>
            </tr>
        </thead>
        <tbody>
            @forelse(($staffRows ?? []) as $row)
                <tr>
                    <td>{{ $row['staff_name'] ?? '-' }}</td>
                    <td>{{ $row['role_label'] ?? '-' }}</td>
                    <td>
                        @php
                            $risk = strtolower((string) ($row['risk'] ?? ''));
                            $riskLabel = $risk === 'red' ? 'High' : ($risk === 'amber' ? 'Medium' : 'Low');
                        @endphp
                        {{ $riskLabel }}
                    </td>
                    <td>{{ $row['training_summary'] ?? '-' }}</td>
                    <td>{{ $row['competency_summary'] ?? '-' }}</td>
                    <td>{{ $row['supervision_summary'] ?? '-' }}</td>
                    <td>{{ $row['dbs_summary'] ?? '-' }}</td>
                    <td>{{ $row['documents_summary'] ?? '-' }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="8">No staff data for the selected filters.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer-meta">
        Generated by: {{ request()->user()?->name ?? 'System' }}<br>
        {{ now()->format('d M Y H:i') }}
    </div>
</body>
</html>
