<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Weekly eMAR Audit</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color: #0f172a; }
        h1 { margin: 0 0 8px; font-size: 18px; }
        h2 { margin: 16px 0 8px; font-size: 13px; }
        .meta { color: #475569; margin-bottom: 14px; }
        .stats span { display: inline-block; margin-right: 16px; margin-bottom: 6px; }
        table { width: 100%; border-collapse: collapse; margin-top: 8px; }
        th, td { border: 1px solid #cbd5e1; padding: 6px; vertical-align: top; }
        th { background: #f1f5f9; text-align: left; }
        .signed { margin-top: 16px; padding: 10px; border: 1px solid #bbf7d0; background: #f0fdf4; }
        .footer-meta { margin-top: 16px; font-size: 10px; color: #475569; text-align: right; }
    </style>
</head>
<body>
    <h1>Weekly eMAR Clinical Audit</h1>
    <div class="meta">Week commencing {{ $weekStart->format('d M Y') }} — ending {{ $weekEnd->format('d M Y') }}</div>

    <div class="stats">
        <span><strong>Total administrations:</strong> {{ $summary['totalAdministrations'] ?? 0 }}</span>
        <span><strong>Given:</strong> {{ $summary['given'] ?? 0 }}</span>
        <span><strong>Refused:</strong> {{ $summary['refused'] ?? 0 }}</span>
        <span><strong>Omitted:</strong> {{ $summary['omitted'] ?? 0 }}</span>
        <span><strong>Delayed:</strong> {{ $summary['delayed'] ?? 0 }}</span>
        <span><strong>Compliance:</strong> {{ $summary['complianceRate'] ?? 0 }}%</span>
    </div>

    @if($audit && $audit->signed_at)
        <div class="signed">
            <strong>Signed off</strong> by {{ $audit->reviewedBy?->name ?? 'Clinical administrator' }}
            on {{ $audit->signed_at->format('d M Y, H:i') }}
            @if($audit->notes)<br>Notes: {{ $audit->notes }}@endif
        </div>
    @endif

    <h2>Exceptions requiring review</h2>
    <table>
        <thead>
            <tr><th>Patient</th><th>Medication</th><th>Status</th><th>Scheduled</th><th>Reason</th></tr>
        </thead>
        <tbody>
            @forelse(($summary['exceptionRows'] ?? []) as $row)
                <tr>
                    <td>{{ $row['patient'] ?? '-' }}</td>
                    <td>{{ $row['medication'] ?? '-' }}</td>
                    <td>{{ $row['status'] ?? '-' }}</td>
                    <td>{{ $row['scheduled_time'] ?? '-' }}</td>
                    <td>{{ $row['reason'] ?? '-' }}</td>
                </tr>
            @empty
                <tr><td colspan="5">No exceptions recorded this week.</td></tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer-meta">
        Generated by: {{ request()->user()?->name ?? 'System' }} — {{ now()->format('d M Y H:i') }}
    </div>
</body>
</html>
