<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Allocare Incident Report</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color: #0f172a; }
        h1 { margin: 0 0 8px; font-size: 18px; text-align: center; }
        .meta { margin-bottom: 12px; color: #475569; text-align: center; }
        .stats { margin-bottom: 14px; text-align: center; }
        .stats span { display: inline-block; margin-right: 14px; }
        table { width: 100%; border-collapse: collapse; }
        th, td { border: 1px solid #cbd5e1; padding: 6px; vertical-align: top; }
        th { background: #f1f5f9; text-align: left; }
        .logo-wrap { text-align: center; margin-bottom: 14px; }
        .logo-fallback { font-size: 30px; font-weight: 700; text-align: center; margin-bottom: 14px; }
        .footer-meta { position: fixed; right: 18px; bottom: 12px; font-size: 10px; color: #475569; text-align: right; }
    </style>
</head>
<body>
    @php
        $logoPath = public_path('images/login-logo.png');
        $logoData = null;
        if (file_exists($logoPath)) {
            $logoData = 'data:image/png;base64,'.base64_encode(file_get_contents($logoPath));
        }
    @endphp
    @if($logoData)
        <div class="logo-wrap"><img src="{{ $logoData }}" alt="Allocare logo" style="height: 110px;" /></div>
    @else
        <div class="logo-fallback">Allocare</div>
    @endif

    <h1>Incident Report</h1>
    <div class="meta"></div>
    <div class="stats">
        <span><strong>Total Incidents:</strong> {{ count($incidents ?? []) }}</span>
    </div>
    <table>
        <thead>
            <tr>
                <th>Category</th><th>Title</th><th>Patient</th><th>Reporter</th><th>Date</th><th>Time</th><th>Status</th><th>Submitted</th>
            </tr>
        </thead>
        <tbody>
            @forelse(($incidents ?? []) as $incident)
                <tr>
                    <td>{{ $incident['category'] ?? '-' }}</td>
                    <td>{{ $incident['title'] ?? '-' }}</td>
                    <td>{{ $incident['patient'] ?? '-' }}</td>
                    <td>{{ $incident['reporter'] ?? '-' }}</td>
                    <td>{{ $incident['incident_date'] ?? '-' }}</td>
                    <td>{{ $incident['incident_time'] ?? '-' }}</td>
                    <td>{{ $incident['status'] ?? '-' }}</td>
                    <td>{{ $incident['submitted_at'] ?? '-' }}</td>
                </tr>
            @empty
                <tr><td colspan="8">No incidents recorded.</td></tr>
            @endforelse
        </tbody>
    </table>
    <div class="footer-meta">
        Generated by: {{ request()->user()?->name ?? 'System' }}<br>
        {{ now()->format('d M Y H:i') }}
    </div>
</body>
</html>
