<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Monthly MAR Chart</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 9px; color: #0f172a; }
        h1 { margin: 0 0 6px; font-size: 16px; text-align: center; }
        h2 { margin: 14px 0 6px; font-size: 12px; }
        .logo-wrap { text-align: center; margin-bottom: 10px; }
        .logo-fallback { text-align: center; font-size: 20px; font-weight: 700; margin-bottom: 10px; }
        .meta { margin-bottom: 10px; color: #475569; text-align: center; font-size: 10px; }
        .legend { margin-bottom: 10px; text-align: center; font-size: 9px; }
        .legend span { margin-right: 10px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 8px; }
        th, td { border: 1px solid #cbd5e1; padding: 3px 2px; text-align: center; vertical-align: middle; }
        th { background: #f1f5f9; }
        td.med { text-align: left; font-weight: 600; min-width: 120px; }
        .inactive { color: #94a3b8; font-style: italic; }
        .footer-meta { margin-top: 12px; font-size: 9px; color: #475569; text-align: right; }
    </style>
</head>
<body>
    @php
        $logoPath = public_path('images/allocare-logo.png');
        $logoData = null;
        if (file_exists($logoPath)) {
            $logoData = 'data:image/png;base64,'.base64_encode(file_get_contents($logoPath));
        }
    @endphp
    @if($logoData)
        <div class="logo-wrap">
            <img src="{{ $logoData }}" alt="AlloCare logo" style="height: 72px;" />
        </div>
    @else
        <div class="logo-fallback">AlloCare</div>
    @endif
    <h1>Monthly Medication Administration Record</h1>
    <div class="meta">
        <strong>{{ $patient->name }}</strong>
        @if($patient->nhs_number) — NHS {{ $patient->nhs_number }} @endif<br>
        {{ $month->format('F Y') }}
    </div>
    <div class="legend">
        <span><strong>G</strong> Given</span>
        <span><strong>D</strong> Delayed</span>
        <span><strong>R</strong> Refused</span>
        <span><strong>O</strong> Omitted</span>
        <span><strong>S</strong> Self-admin</span>
        <span><strong>P</strong> PRN</span>
        <span><strong>—</strong> No record</span>
    </div>

    <h2>Scheduled medications</h2>
    <table>
        <thead>
            <tr>
                <th class="med">Medication</th>
                <th>Time</th>
                @foreach($days as $day)
                    <th>{{ $day }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @forelse($scheduledRows as $row)
                <tr>
                    <td class="med {{ !empty($row['inactive']) ? 'inactive' : '' }}">
                        {{ $row['name'] }}{{ !empty($row['inactive']) ? ' (inactive)' : '' }}
                        {{ $row['dose'] ? '('.$row['dose'].')' : '' }}
                    </td>
                    <td>{{ $row['time'] ?: '—' }}</td>
                    @foreach($row['cells'] as $cell)
                        <td>{{ $cell }}</td>
                    @endforeach
                </tr>
            @empty
                <tr><td colspan="{{ 2 + count($days) }}">No scheduled medications for this period.</td></tr>
            @endforelse
        </tbody>
    </table>

    @if(!empty($prnRows))
        <h2>PRN medications</h2>
        <table>
            <thead>
                <tr>
                    <th class="med">Medication</th>
                    <th>Type</th>
                    @foreach($days as $day)
                        <th>{{ $day }}</th>
                    @endforeach
                </tr>
            </thead>
            <tbody>
                @foreach($prnRows as $row)
                    <tr>
                        <td class="med {{ !empty($row['inactive']) ? 'inactive' : '' }}">
                            {{ $row['name'] }}{{ !empty($row['inactive']) ? ' (inactive)' : '' }}
                            {{ $row['dose'] ? '('.$row['dose'].')' : '' }}
                        </td>
                        <td>PRN</td>
                        @foreach($row['cells'] as $cell)
                            <td>{{ $cell }}</td>
                        @endforeach
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endif

    <div class="footer-meta">
        Generated by: {{ request()->user()?->name ?? 'System' }} — {{ now()->format('d M Y H:i') }}
    </div>
</body>
</html>
