<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Allocare Medication Report</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color: #0f172a; }
        h1 { margin: 0 0 8px; font-size: 18px; text-align: center; }
        .meta { margin-bottom: 12px; color: #475569; text-align: center; }
        .stats { margin-bottom: 14px; text-align: center; }
        .stats span { display: inline-block; margin-right: 14px; }
        table { width: 100%; border-collapse: collapse; }
        th, td { border: 1px solid #cbd5e1; padding: 6px; vertical-align: top; }
        th { background: #f1f5f9; text-align: left; }
        .logo-wrap { text-align: center; margin-bottom: 14px; }
        .logo-fallback { font-size: 30px; font-weight: 700; text-align: center; margin-bottom: 14px; }
        .footer-meta { position: fixed; right: 18px; bottom: 12px; font-size: 10px; color: #475569; text-align: right; }
    </style>
</head>
<body>
    @php
        $logoPath = public_path('images/login-logo.png');
        $logoData = null;
        if (file_exists($logoPath)) {
            $logoData = 'data:image/png;base64,'.base64_encode(file_get_contents($logoPath));
        }
    @endphp
    @if($logoData)
        <div class="logo-wrap"><img src="{{ $logoData }}" alt="Allocare logo" style="height: 110px;" /></div>
    @else
        <div class="logo-fallback">Allocare</div>
    @endif

    <h1>Medication Report</h1>
    <div class="meta">From {{ $from->format('d M Y') }} to {{ $to->format('d M Y') }}</div>
    <div class="stats">
        <span><strong>Total Records:</strong> {{ count($administrations ?? []) }}</span>
    </div>
    <table>
        <thead>
            <tr>
                <th>Patient</th><th>Medication</th><th>Status</th><th>Administered By</th><th>Scheduled Time</th><th>Updated time</th><th>Timeliness</th><th>Reason</th>
            </tr>
        </thead>
        <tbody>
            @forelse(($administrations ?? []) as $a)
                <tr>
                    <td>{{ $a->patient?->name ?? '-' }}</td>
                    <td>{{ $a->medication?->name ?? '-' }}</td>
                    <td>{{ $a->status ?? '-' }}</td>
                    <td>{{ $a->administeredBy?->name ?? '-' }}</td>
                    <td>{{ $a->scheduled_for?->format('d M Y H:i') ?? '-' }}</td>
                    <td>{{ $a->updated_at?->format('d M Y H:i') ?? '-' }}</td>
                    <td>{{ medication_administration_timeliness($a) }}</td>
                    <td>{{ $a->reason ?? '-' }}</td>
                </tr>
            @empty
                <tr><td colspan="8">No medication administrations in selected period.</td></tr>
            @endforelse
        </tbody>
    </table>
    <div class="footer-meta">
        Generated by: {{ request()->user()?->name ?? 'System' }}<br>
        {{ now()->format('d M Y H:i') }}
    </div>
</body>
</html>
