<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>CQC Medication Exception Report</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 10px; color: #0f172a; }
        h1 { margin: 0 0 4px; font-size: 17px; text-align: center; }
        .subtitle { text-align: center; color: #64748b; margin-bottom: 10px; font-size: 11px; }
        .meta { margin-bottom: 12px; color: #475569; text-align: center; }
        .notice { margin-bottom: 12px; padding: 8px; border: 1px solid #fecaca; background: #fef2f2; font-size: 10px; }
        table { width: 100%; border-collapse: collapse; }
        th, td { border: 1px solid #cbd5e1; padding: 5px; vertical-align: top; }
        th { background: #f1f5f9; text-align: left; }
        .footer-meta { margin-top: 14px; font-size: 9px; color: #475569; text-align: right; }
    </style>
</head>
<body>
    <h1>Medication Exception Report</h1>
    <div class="subtitle">CQC inspection evidence — refused, omitted, and delayed doses only</div>
    <div class="meta">Period: {{ $from->format('d M Y') }} to {{ $to->format('d M Y') }}</div>
    <div class="notice">
        This report lists all medication administration exceptions requiring clinical review and follow-up action.
        Records are permanently retained in the service user medication history.
    </div>
    <table>
        <thead>
            <tr>
                <th>Patient</th>
                <th>NHS No.</th>
                <th>Medication</th>
                <th>Exception</th>
                <th>Scheduled</th>
                <th>Recorded</th>
                <th>Recorded By</th>
                <th>Reason</th>
                <th>Rescheduled</th>
                <th>Witness</th>
            </tr>
        </thead>
        <tbody>
            @forelse($administrations as $a)
                <tr>
                    <td>{{ $a->patient?->name ?? '-' }}</td>
                    <td>{{ $a->patient?->nhs_number ?? '-' }}</td>
                    <td>{{ $a->medication?->name ?? '-' }}</td>
                    <td>{{ strtoupper((string) $a->status) }}</td>
                    <td>{{ $a->scheduled_for?->format('d M Y H:i') ?? '-' }}</td>
                    <td>{{ $a->updated_at?->format('d M Y H:i') ?? '-' }}</td>
                    <td>{{ $a->administeredBy?->name ?? '-' }}</td>
                    <td>{{ $a->reason ?? '-' }}</td>
                    <td>{{ $a->rescheduled_for?->format('d M Y H:i') ?? '-' }}</td>
                    <td>{{ $a->witness_name ?? '-' }}</td>
                </tr>
            @empty
                <tr><td colspan="10">No medication exceptions in the selected period.</td></tr>
            @endforelse
        </tbody>
    </table>
    <div class="footer-meta">
        Generated by: {{ request()->user()?->name ?? 'System' }} — {{ now()->format('d M Y H:i') }}
    </div>
</body>
</html>
