<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Medication History</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 10px; color: #0f172a; }
        h1 { margin: 0 0 8px; font-size: 17px; text-align: center; }
        .meta { margin-bottom: 12px; color: #475569; text-align: center; }
        .notice { margin-bottom: 10px; font-size: 10px; color: #64748b; text-align: center; }
        table { width: 100%; border-collapse: collapse; }
        th, td { border: 1px solid #cbd5e1; padding: 5px; vertical-align: top; }
        th { background: #f1f5f9; text-align: left; }
        .voided { color: #94a3b8; font-style: italic; }
        .footer-meta { margin-top: 14px; font-size: 9px; color: #475569; text-align: right; }
    </style>
</head>
<body>
    <h1>Individual Medication Administration History</h1>
    <div class="meta">
        <strong>{{ $patient->name }}</strong>
        @if($patient->nhs_number) — NHS {{ $patient->nhs_number }} @endif<br>
        {{ $from->format('d M Y') }} to {{ $to->format('d M Y') }}
    </div>
    <div class="notice">Permanent clinical record — administration entries cannot be deleted from the system.</div>
    <table>
        <thead>
            <tr>
                <th>Medication</th>
                <th>Status</th>
                <th>Scheduled</th>
                <th>Updated</th>
                <th>Recorded By</th>
                <th>Reason</th>
                <th>Witness</th>
                <th>Retention</th>
            </tr>
        </thead>
        <tbody>
            @forelse($administrations as $a)
                <tr class="{{ $a->voided_at ? 'voided' : '' }}">
                    <td>{{ $a->medication?->name ?? '-' }}</td>
                    <td>{{ $a->status ?? '-' }}</td>
                    <td>{{ $a->scheduled_for?->format('d M Y H:i') ?? '-' }}</td>
                    <td>{{ $a->updated_at?->format('d M Y H:i') ?? '-' }}</td>
                    <td>{{ $a->administeredBy?->name ?? '-' }}</td>
                    <td>{{ $a->reason ?? '-' }}</td>
                    <td>{{ $a->witness_name ?? '-' }}</td>
                    <td>
                        @if($a->voided_at)
                            Voided {{ $a->voided_at->format('d M Y H:i') }} — retained
                        @else
                            Active record
                        @endif
                    </td>
                </tr>
            @empty
                <tr><td colspan="8">No medication administrations in the selected period.</td></tr>
            @endforelse
        </tbody>
    </table>
    <div class="footer-meta">
        Generated by: {{ request()->user()?->name ?? 'System' }} — {{ now()->format('d M Y H:i') }}
    </div>
</body>
</html>
