<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Risk Assessment</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color: #0f172a; line-height: 1.45; }
        h1 { margin: 0 0 4px; font-size: 18px; text-align: center; }
        h2 { margin: 16px 0 6px; font-size: 13px; border-bottom: 1px solid #cbd5e1; padding-bottom: 4px; }
        .logo-wrap { text-align: center; margin-bottom: 10px; }
        .logo-fallback { text-align: center; font-size: 20px; font-weight: 700; margin-bottom: 10px; }
        .meta { margin-bottom: 14px; color: #475569; text-align: center; font-size: 10px; }
        .badge { display: inline-block; padding: 3px 8px; border-radius: 4px; font-size: 10px; font-weight: bold; text-transform: uppercase; }
        .badge-high { background: #ffe4e6; color: #be123c; }
        .badge-moderate { background: #fef3c7; color: #b45309; }
        .badge-low { background: #d1fae5; color: #047857; }
        .field { margin-bottom: 10px; }
        .label { font-size: 9px; font-weight: bold; text-transform: uppercase; color: #64748b; margin-bottom: 2px; }
        .value { white-space: pre-wrap; }
        .grid { width: 100%; border-collapse: collapse; margin-bottom: 8px; }
        .grid td { padding: 4px 8px 4px 0; vertical-align: top; width: 50%; }
        .footer-meta { margin-top: 20px; font-size: 9px; color: #64748b; text-align: right; border-top: 1px solid #e2e8f0; padding-top: 8px; }
        .suggested { font-size: 9px; color: #64748b; margin-top: 4px; }
    </style>
</head>
<body>
    @php
        $logoPath = public_path('images/allocare-logo.png');
        $logoData = null;
        if (file_exists($logoPath)) {
            $logoData = 'data:image/png;base64,'.base64_encode(file_get_contents($logoPath));
        }
        $level = $assessment['risk_level'] ?? 'moderate';
        $badgeClass = match ($level) {
            'high' => 'badge-high',
            'low' => 'badge-low',
            default => 'badge-moderate',
        };
    @endphp
    @if($logoData)
        <div class="logo-wrap">
            <img src="{{ $logoData }}" alt="AlloCare logo" style="height: 64px;" />
        </div>
    @else
        <div class="logo-fallback">AlloCare</div>
    @endif
    <h1>{{ $title }}</h1>
    <div class="meta">
        <strong>{{ $patient->name }}</strong>
        @if($patient->nhs_number) — NHS {{ $patient->nhs_number }} @endif
        @if($patient->reference) — {{ $patient->reference }} @endif
        <br>
        Risk assessment export — {{ now()->format('d M Y H:i') }}
    </div>

    <table class="grid">
        <tr>
            <td>
                <div class="label">Risk level</div>
                <span class="badge {{ $badgeClass }}">{{ $assessment['risk_level_label'] ?? '—' }}</span>
            </td>
            <td>
                <div class="label">Status</div>
                <div class="value">{{ $assessment['status_label'] ?? '—' }}</div>
            </td>
        </tr>
        <tr>
            <td>
                <div class="label">Review owner</div>
                <div class="value">{{ $assessment['owner_name'] ?? '—' }}</div>
            </td>
            <td>
                <div class="label">Last reviewed</div>
                <div class="value">{{ $assessment['last_reviewed_at_label'] ?? '—' }}</div>
            </td>
        </tr>
        <tr>
            <td>
                <div class="label">Next review due</div>
                <div class="value">{{ $assessment['next_review_due_at_label'] ?? '—' }}</div>
            </td>
            <td>
                <div class="label">Review cycle</div>
                <div class="value">{{ ($assessment['review_cycle_months'] ?? '—') }} months</div>
            </td>
        </tr>
    </table>

    <h2>Triggers / risk factors</h2>
    <div class="field value">{{ $assessment['triggers'] ?? 'Not recorded' }}</div>

    <h2>Current controls</h2>
    <div class="field value">{{ $assessment['current_controls'] ?? 'Not recorded' }}</div>
    @if(!empty($suggestedControls))
        <p class="suggested">Template suggestions: {{ implode(' · ', $suggestedControls) }}</p>
    @endif

    <h2>Mitigation / action plan</h2>
    <div class="field value">{{ $assessment['mitigation_plan'] ?? 'Not recorded' }}</div>

    <div class="footer-meta">
        Recorded by: {{ $assessment['author_name'] ?? 'Unknown' }}
        @if(!empty($assessment['updated_at_label'])) — last saved {{ $assessment['updated_at_label'] }} @endif
        <br>
        Generated by: {{ $generatedBy }} — AlloCare
    </div>
</body>
</html>
