<?php

return [
    'routes' => [
        'Oral',
        'Topical',
        'Inhaled',
        'PEG',
        'Subcutaneous',
        'Intravenous',
        'Intramuscular',
        'Rectal',
        'Transdermal',
        'Sublingual',
        'Other',
    ],
    'dose_units' => [
        'mg',
        'g',
        'mcg',
        'ml',
        'units',
        'tablets',
        'capsules',
        'puffs',
        'patches',
        'applications',
        'drops',
    ],
    'allergy_cross_reactivity' => [
        'penicillin' => ['penicillin', 'amoxicillin', 'ampicillin', 'flucloxacillin', 'co-amoxiclav', 'phenoxymethylpenicillin'],
        'sulfa' => ['sulfamethoxazole', 'trimethoprim', 'co-trimoxazole', 'sulfa'],
        'nsaid' => ['ibuprofen', 'naproxen', 'aspirin', 'diclofenac', 'nsaid'],
    ],
    'frequency_presets' => [
        'once_daily' => ['08:00'],
        'twice_daily' => ['08:00', '20:00'],
        'three_times_daily' => ['08:00', '14:00', '22:00'],
        'four_times_daily' => ['06:00', '12:00', '18:00', '22:00'],
        'every_8h' => ['06:00', '14:00', '22:00'],
        'every_12h' => ['08:00', '20:00'],
        'weekly' => ['08:00'],
        'custom' => null,
    ],
    'mar_reason_presets' => [
        'Service user declined',
        'Asleep',
        'Nausea / vomiting',
        'Nil by mouth',
        'Refused after explanation',
        'Not available / away from home',
        'Equipment unavailable',
        'Other',
    ],
    'prn_effectiveness_ratings' => [
        'effective' => 'Effective',
        'partially_effective' => 'Partially effective',
        'not_effective' => 'Not effective',
        'too_soon_to_assess' => 'Too soon to assess',
    ],
];
